name: Build and deploy Python app to Azure Web App - daywell-backend1

on:
  push:
    contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        working-directory: backend
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: backend
        run: |
          source venv/bin/activate
          pip install -r backend/requirements.txt

      # Optional: Add step to run tests here

      - name: Upload backend artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-backend
          path: |
            backend/
            !backend/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: python-backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_417D4E18F8E243BE90C07FAADEEEBB37 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0EDD70053BC447FD9C14A6604C524AD0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_321972BA5B024FC089BD627D51F20494 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'daywell-backend1'
          slot-name: 'Production'
          package: backend/    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
